import XCTest

@testable import Sentori

/// The Swift hash must equal the TypeScript one for every input, or a
/// device stops matching the events from the same person and the push
/// that was supposed to reach them reaches nobody — silently, on the
/// one path where nobody is watching.
///
/// The vectors are generated by `sdk/core/src/identity.ts` itself
/// (`scripts/gen-identity-vectors.mjs`), so this asserts against what
/// the other implementation actually does rather than against what
/// this file's author believed it does.
final class SentoriIdentityTests: XCTestCase {

    private struct Vector: Decodable {
        let keyType: String
        let raw: String
        let sha256Hex: String
    }
    private struct Fixture: Decodable {
        let vectors: [Vector]
    }

    private func loadVectors() throws -> [Vector] {
        // Up from Tests/SentoriTests/ to the package, then to the
        // shared fixtures Kotlin reads too. `#filePath` rather than a
        // bundle resource: SwiftPM would need the JSON declared as a
        // target resource, and one copy shared with Android is the
        // whole point.
        let here = URL(fileURLWithPath: #filePath)
        let fixture = here
            .deletingLastPathComponent()  // SentoriTests
            .deletingLastPathComponent()  // Tests
            .deletingLastPathComponent()  // ios
            .deletingLastPathComponent()  // native
            .appendingPathComponent("fixtures/identity-vectors.json")
        let data = try Data(contentsOf: fixture)
        return try JSONDecoder().decode(Fixture.self, from: data).vectors
    }

    func testMatchesTheTypeScriptImplementation() throws {
        let vectors = try loadVectors()
        XCTAssertGreaterThanOrEqual(
            vectors.count, 10,
            "fixture looks truncated — a file that reads as empty passes everything"
        )
        for v in vectors {
            XCTAssertEqual(
                SentoriIdentity.hash(keyType: v.keyType, value: v.raw),
                v.sha256Hex,
                "\(v.keyType) / \(v.raw.prefix(40))"
            )
        }
    }

    func testEmptyAndBlankProduceNoKey() {
        XCTAssertNil(SentoriIdentity.hash(keyType: "id", value: ""))
        XCTAssertNil(SentoriIdentity.hash(keyType: "id", value: "   "))
        XCTAssertNil(SentoriIdentity.hash(keyType: "email", value: " \n "))
        // A phone with no digits normalises away entirely.
        XCTAssertNil(SentoriIdentity.hash(keyType: "phone", value: "(--) --"))
    }

    func testUserKeyPrefersIdAndFallsBackToEmail() {
        let byId = SentoriIdentity.userKey(id: "usr_123", email: "a@b.com")
        XCTAssertEqual(byId, SentoriIdentity.hash(keyType: "id", value: "usr_123"))

        let byEmail = SentoriIdentity.userKey(id: nil, email: "A@B.com")
        XCTAssertEqual(byEmail, SentoriIdentity.hash(keyType: "email", value: "A@B.com"))

        // A blank id must fall through rather than win and yield nil —
        // `sentori.user({ id: "" })` is a wiring mistake, not a
        // decision to become unaddressable.
        XCTAssertEqual(SentoriIdentity.userKey(id: "  ", email: "a@b.com"), byEmail)

        XCTAssertNil(SentoriIdentity.userKey(id: nil, email: nil))
    }

    func testOAuthSubjectsAreLeftExactlyAsGiven() {
        // Opaque provider ids: trimming or lowercasing one would
        // change an identifier we did not define.
        XCTAssertEqual(SentoriIdentity.normalise(keyType: "googleSub", raw: " Ab "), " Ab ")
        XCTAssertEqual(SentoriIdentity.normalise(keyType: "appleSub", raw: "X.Y"), "X.Y")
    }
}
