//! Per-request correlation id — uuid-v7 generated by Tower middleware,
//! threaded into the tracing span as `correlation_id`, and emitted as
//! the `X-Sentori-Correlation-Id` response header.
//!
//! Every other observability + error feature reads this id back. The
//! contract:
//!
//! 1. The id is set BEFORE any handler runs (so handlers can read it
//!    via the request extension if they want to embed it in a 4xx
//!    body).
//! 2. The id is uuid-v7 so it sorts lexicographically by creation
//!    time — log greps are time-ordered.
//! 3. The id is fresh per request; we don't honour an incoming
//!    `X-Sentori-Correlation-Id` header. Forwarding upstream
//!    correlation ids is a v1.2 concern (would let CI's
//!    request-tracer tag flow through).
//!
//! Set + extract:
//! ```ignore
//! use sentori_server::correlation_id::CorrelationId;
//!
//! async fn handler(Extension(cid): Extension<CorrelationId>) -> impl IntoResponse {
//!   tracing::info!(correlation_id = %cid, "received request");
//!   ...
//! }
//! ```

use axum::{
    body::Body,
    extract::Request,
    http::{HeaderName, HeaderValue},
    middleware::Next,
    response::Response,
};
use uuid::Uuid;

tokio::task_local! {
    /// The correlation id scoped to the currently-running request. Set
    /// by [`correlation_id_middleware`] and readable by any code in
    /// the task tree, including [`AppError::into_response`] which has
    /// no access to the request itself.
    pub static CURRENT_CORRELATION_ID: Uuid;
}

/// Return the correlation id for the current request task, or the
/// nil uuid if none is set (e.g. running outside the Tower pipeline,
/// like unit tests).
pub fn current() -> Uuid {
    CURRENT_CORRELATION_ID
        .try_with(|id| *id)
        .unwrap_or(Uuid::nil())
}

/// Per-request correlation id. Cheap to clone (it's a `Uuid` inside).
#[derive(Clone, Copy, Debug)]
pub struct CorrelationId(pub Uuid);

impl std::fmt::Display for CorrelationId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}

/// Header name we use on the response.
pub const HEADER_NAME: &str = "x-sentori-correlation-id";

/// Axum middleware that mints a fresh uuid-v7 per request, stores it
/// as a request extension (so handlers can read it via
/// `Extension<CorrelationId>`), and adds the `X-Sentori-Correlation-Id`
/// header to the outgoing response.
pub async fn correlation_id_middleware(mut req: Request<Body>, next: Next) -> Response {
    let id = Uuid::now_v7();
    let cid = CorrelationId(id);

    // Stash on the request extensions so handlers + error converters
    // can read it (e.g. to embed in a structured error body).
    req.extensions_mut().insert(cid);

    // Also scope as a task-local so AppError::IntoResponse — which
    // has no access to the request — can pick it up. CURRENT_CORRELATION_ID
    // is the v1.1 standard way to read the cid from any code that
    // runs inside the request task tree.
    let mut resp = CURRENT_CORRELATION_ID
        .scope(id, async move { next.run(req).await })
        .await;

    // Add to response headers. We construct the HeaderValue from a
    // hyphenated uuid string, which is always ASCII so the unwrap is
    // sound.
    if let Ok(value) = HeaderValue::from_str(&id.to_string()) {
        let name = HeaderName::from_static(HEADER_NAME);
        resp.headers_mut().insert(name, value);
    }

    resp
}
