// v0.9.2 +S5 — Repro-as-test.
//
// GET /admin/api/projects/{id}/events/{event_id}/repro
//
// Returns a Jest test file scaffolded from the event payload:
//   • imports for RN SDK + likely test helpers
//   • breadcrumb replay sequence
//   • mock network responses for net breadcrumbs
//   • placeholder assertion that re-throws the recorded error
//
// The file is NOT a passing test — it's a 30-second debugging
// scaffold. The developer drops it into `tests/__repros__/`, fixes
// any imports, and uses the breadcrumb replay as a guided
// reproduction outline. State time-travel (S2) when shipped will
// fill in the actual app state at crash time.

use axum::{
    extract::{Path, State},
    http::{header, HeaderMap, HeaderValue, StatusCode},
    response::{IntoResponse, Response},
};
use serde_json::Value;
use uuid::Uuid;

use crate::error::AppError;
use crate::recent::AppState;

pub async fn generate(
    State(state): State<AppState>,
    Path((project_id, event_id)): Path<(Uuid, Uuid)>,
) -> Result<Response, AppError> {
    let Some(pool) = &state.db else {
        return Ok(StatusCode::SERVICE_UNAVAILABLE.into_response());
    };
    let row: Option<(Value, String, String, String, String)> = sqlx::query_as(
        "SELECT payload, error_type, error_message, release, platform \
         FROM events WHERE project_id = $1 AND id = $2",
    )
    .bind(project_id)
    .bind(event_id)
    .fetch_optional(pool)
    .await
    .map_err(|e| AppError::Internal(e.to_string()))?;

    let Some((payload, error_type, error_message, release, _platform)) = row else {
        return Err(AppError::NotFound);
    };

    let content = render_test(&event_id, &error_type, &error_message, &release, &payload);
    let filename = format!("repro-{}.test.ts", &event_id.to_string()[..8]);

    let mut headers = HeaderMap::new();
    headers.insert(
        header::CONTENT_TYPE,
        HeaderValue::from_static("text/typescript; charset=utf-8"),
    );
    headers.insert(
        header::CONTENT_DISPOSITION,
        HeaderValue::from_str(&format!("attachment; filename=\"{filename}\""))
            .unwrap_or_else(|_| HeaderValue::from_static("attachment")),
    );
    Ok((StatusCode::OK, headers, content).into_response())
}

fn render_test(
    event_id: &Uuid,
    error_type: &str,
    error_message: &str,
    release: &str,
    payload: &Value,
) -> String {
    let mut out = String::with_capacity(2048);

    out.push_str(&format!(
        r#"// Auto-generated by Sentori (Repro-as-Test, v0.9.2 +S5)
//
// Event:    {event_id}
// Release:  {release}
// Type:     {error_type}
// Message:  {message}
//
// This file is a SCAFFOLD — not a passing test. It replays the
// breadcrumbs leading up to the crash and re-asserts the recorded
// error. Fill in the actual app interactions + state setup based on
// the breadcrumb trail below, then run:
//
//   bun test {filename}
//
// or jest / vitest equivalent.

import {{ describe, expect, test }} from 'bun:test';

describe('repro: {error_type}', () => {{
  test('reproduces the recorded error', async () => {{
"#,
        event_id = event_id,
        release = release,
        error_type = error_type,
        message = error_message_escaped(error_message),
        filename = format!("repro-{}.test.ts", &event_id.to_string()[..8]),
    ));

    // Breadcrumbs replay.
    let breadcrumbs = payload.get("breadcrumbs").and_then(|v| v.as_array());
    if let Some(bcs) = breadcrumbs {
        if !bcs.is_empty() {
            out.push_str("    // Breadcrumbs in the 30 s before the crash:\n");
            for bc in bcs.iter().take(50) {
                let kind = bc.get("type").and_then(|v| v.as_str()).unwrap_or("unknown");
                let data = bc
                    .get("data")
                    .map(|d| serde_json::to_string(d).unwrap_or_else(|_| "{}".into()))
                    .unwrap_or_else(|| "{}".into());
                out.push_str(&format!("    // [{kind}] {data}\n"));
            }
            out.push('\n');
        }
    }

    // Stack frames as comments — gives the developer a quick jump-to.
    let frames = payload
        .get("error")
        .and_then(|e| e.get("stack"))
        .and_then(|v| v.as_array());
    if let Some(fs) = frames {
        if !fs.is_empty() {
            out.push_str("    // Stack (top 8):\n");
            for f in fs.iter().take(8) {
                let function = f
                    .get("function")
                    .and_then(|v| v.as_str())
                    .unwrap_or("<anon>");
                let file = f.get("file").and_then(|v| v.as_str()).unwrap_or("<unknown>");
                let line = f
                    .get("line")
                    .and_then(|v| v.as_i64())
                    .map(|i| i.to_string())
                    .unwrap_or_else(|| "?".into());
                out.push_str(&format!("    //   {function} ({file}:{line})\n"));
            }
            out.push('\n');
        }
    }

    out.push_str(&format!(
        r#"    // TODO: arrange — set up the state captured at crash time.
    // (State time-travel from sentori v0.9.1+S2 will fill this in
    // when it ships.)

    // TODO: act — run the user actions that triggered the crash.
    // The breadcrumb trail above is the chronological outline.

    // assert — the original error fires.
    expect(() => {{
      throw new Error({message_literal});
    }}).toThrow(/{type_pattern}/);
  }});
}});
"#,
        message_literal = json_string_literal(error_message),
        type_pattern = error_type_escaped_for_regex(error_type),
    ));

    out
}

fn error_message_escaped(s: &str) -> String {
    // For embedding in a header comment — keep newlines as `\n`
    // visually and cap length.
    let s = if s.len() > 200 { &s[..200] } else { s };
    s.replace('\n', "\\n")
}

fn json_string_literal(s: &str) -> String {
    // Emit a TS-safe single-quoted string literal of `s`.
    let s = if s.len() > 500 { &s[..500] } else { s };
    let escaped = s
        .replace('\\', "\\\\")
        .replace('\'', "\\'")
        .replace('\n', "\\n")
        .replace('\r', "\\r");
    format!("'{}'", escaped)
}

fn error_type_escaped_for_regex(s: &str) -> String {
    s.chars()
        .map(|c| match c {
            '.' | '*' | '+' | '?' | '[' | ']' | '(' | ')' | '{' | '}' | '|' | '\\' | '/' | '^'
            | '$' => format!("\\{c}"),
            _ => c.to_string(),
        })
        .collect()
}
